function WeightTracker() {
    this.showWeekDate = "";
    this.pageWeekDate = "";
    this.weekDate = "";
    this.dateOfWeekDate = "";
    this.enterDate = "";
    this.showDate = "";
    this.weight = "";
    this.note = "";
    this.milestonType = "";
    this.lostWeight = "";
    this.lostWeightTotal = "";
    this.weightClass = "";
    this.noWeight = "";
    this.noStar = "";
    this.showMileston = "";
    this.prePath = "";
    this.editFlag = "";
    this.messageCode = "";
    this.initialWeight = "";
    this.weightGoal = "";
    this.dptChanged = "";
    this.highestPriorityMilestone = "";
    this.healthWeightMin = "";
    this.healthWeightMax = "";
    this.milestones = [];
    this.allMilestones = [];
}